<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="bixi" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find bixi_description)/urdf/wheel.urdf.xacro" />
    <!-- Constants for robot dimensions -->
    <xacro:property name="M_PI" value="3.1415926535897931"/>

    <!-- this section must be changed according to the real robot -->
    <!-- Base Size -->
    <property name="base_mass" value="10" />
    <property name="base_x_size" value="0.8" />
    <property name="base_y_size" value="0.4" />
    <property name="base_z_size" value="0.1" />

    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheelbase" value="0.6" />
    <xacro:property name="track" value="0.55" />
    <xacro:property name="wheel_vertical_offset" value="0.05" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_radius" value="0.075" />


    <!-- base link is the center of the robot's bottom plate -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://bixi_description/meshes/chasis.dae" scale="1 1 1" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 0" />
            <inertia ixx="${1/12*base_mass*(base_x_size*base_x_size + base_z_size*base_z_size)}"
                iyy="${1/12*base_mass*(base_y_size*base_y_size + base_z_size*base_z_size)}"
                izz="${1/12*base_mass*(base_y_size*base_y_size + base_x_size*base_x_size)}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <!-- Base footprint is on the ground under the robot, NOT IN USE, use baselink as the root >
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_vertical_offset+wheel_radius}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint -->

    <!-- Husky wheel macros -->
    <xacro:wheel ccw="1" wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} -${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel ccw="0" wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} -${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel ccw="0" wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} -${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>
    <xacro:wheel ccw="1" wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} -${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>

</robot>
